[tool.poetry]
name = "stripe-checkout"
version = "0.1.0"
description = ""
authors = ["Oleg Gera <hi@oleggera.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
